In [ ]:
import numpy as np
import pandas as pd
import matplotlib as mp
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
import platform

warnings.filterwarnings(action='ignore')  # 경고 메시지를 무시하고 숨기기  warnings.filterwarnings('ignore')
# warnings.filterwarnings(action='default')   # 숨긴 경고 메시지 다시 보이기

#모든 컬럼들이 보이도록 설정한다.
pd.options.display.max_columns=829

In [2]:
# OS에 따른 한글 폰트 설정
if platform.system() == 'Windows':
    plt.rc('font', family='Malgun Gothic')  # 윈도우: 맑은 고딕
elif platform.system() == 'Darwin':
    plt.rc('font', family='AppleGothic')    # 맥: 애플 고딕
else:
    plt.rc('font', family='NanumBarunGothic') # 리눅스

# 마이너스 기호 깨짐 방지
plt.rc('axes', unicode_minus=False)

In [4]:
# --------------------------------
# 1. 한글 CSV 안전하게 읽는 함수
# --------------------------------
def read_csv_korean(path):
    for enc in ["utf-8", "cp949", "euc-kr"]:
        try:
            return pd.read_csv(path, encoding=enc)
        except UnicodeDecodeError:
            continue
    raise UnicodeDecodeError(f"인코딩 실패: {path}")

# --------------------------------
# 2. 파일 경로
# --------------------------------
file_1 = "./source/시군구_성_월별_출생_202607.csv"

# --------------------------------
# 3. CSV 파일 읽기
# --------------------------------
df_kosis = read_csv_korean(file_1)

df_kosis.head()

,시군구별,1997.01,1997.01.1,1997.01.2,1997.02,1997.02.1,1997.02.2,1997.03,1997.03.1,1997.03.2,1997.04,1997.04.1,1997.04.2,1997.05,1997.05.1,1997.05.2,1997.06,1997.06.1,1997.06.2,1997.07,1997.07.1,1997.07.2,1997.08,1997.08.1,1997.08.2,1997.09,1997.09.1,1997.09.2,1997.10,1997.10.1,1997.10.2,1997.11,1997.11.1,1997.11.2,1997.12,1997.12.1,1997.12.2,1998.01,1998.01.1,1998.01.2,1998.02,1998.02.1,1998.02.2,1998.03,1998.03.1,1998.03.2,1998.04,1998.04.1,1998.04.2,1998.05,1998.05.1,1998.05.2,1998.06,1998.06.1,1998.06.2,1998.07,1998.07.1,1998.07.2,1998.08,1998.08.1,1998.08.2,1998.09,1998.09.1,1998.09.2,1998.10,1998.10.1,1998.10.2,1998.11,1998.11.1,1998.11.2,1998.12,1998.12.1,1998.12.2,1999.01,1999.01.1,1999.01.2,1999.02,1999.02.1,1999.02.2,1999.03,1999.03.1,1999.03.2,1999.04,1999.04.1,1999.04.2,1999.05,1999.05.1,1999.05.2,1999.06,1999.06.1,1999.06.2,1999.07,1999.07.1,1999.07.2,1999.08,1999.08.1,1999.08.2,1999.09,1999.09.1,1999.09.2,1999.10,1999.10.1,1999.10.2,1999.11,1999.11.1,1999.11.2,1999.12,1999.12.1,1999.12.2,2000.01,2000.01.1,2000.01.2,2000.02,2000.02.1,2000.02.2,2000.03,2000.03.1,2000.03.2,2000.04,2000.04.1,2000.04.2,2000.05,2000.05.1,2000.05.2,2000.06,2000.06.1,2000.06.2,2000.07,2000.07.1,2000.07.2,2000.08,2000.08.1,2000.08.2,2000.09,2000.09.1,2000.09.2,2000.10,2000.10.1,2000.10.2,2000.11,2000.11.1,2000.11.2,2000.12,2000.12.1,2000.12.2,2001.01,2001.01.1,2001.01.2,2001.02,2001.02.1,2001.02.2,2001.03,2001.03.1,2001.03.2,2001.04,2001.04.1,2001.04.2,2001.05,2001.05.1,2001.05.2,2001.06,2001.06.1,2001.06.2,2001.07,2001.07.1,2001.07.2,2001.08,2001.08.1,2001.08.2,2001.09,2001.09.1,2001.09.2,2001.10,2001.10.1,2001.10.2,2001.11,2001.11.1,2001.11.2,2001.12,2001.12.1,2001.12.2,2002.01,2002.01.1,2002.01.2,2002.02,2002.02.1,2002.02.2,2002.03,2002.03.1,2002.03.2,2002.04,2002.04.1,2002.04.2,2002.05,2002.05.1,2002.05.2,2002.06,2002.06.1,2002.06.2,2002.07,2002.07.1,2002.07.2,2002.08,2002.08.1,2002.08.2,2002.09,2002.09.1,2002.09.2,2002.10,2002.10.1,2002.10.2,2002.11,2002.11.1,2002.11.2,2002.12,2002.12.1,2002.12.2,2003.01,2003.01.1,2003.01.2,2003.02,2003.02.1,2003.02.2,2003.03,2003.03.1,2003.03.2,2003.04,2003.04.1,2003.04.2,2003.05,2003.05.1,2003.05.2,2003.06,2003.06.1,2003.06.2,2003.07,2003.07.1,2003.07.2,2003.08,2003.08.1,2003.08.2,2003.09,2003.09.1,2003.09.2,2003.10,2003.10.1,2003.10.2,2003.11,2003.11.1,2003.11.2,2003.12,2003.12.1,2003.12.2,2004.01,2004.01.1,2004.01.2,2004.02,2004.02.1,2004.02.2,2004.03,2004.03.1,2004.03.2,2004.04,2004.04.1,2004.04.2,2004.05,2004.05.1,2004.05.2,2004.06,2004.06.1,2004.06.2,2004.07,2004.07.1,2004.07.2,2004.08,2004.08.1,2004.08.2,2004.09,2004.09.1,2004.09.2,2004.10,2004.10.1,2004.10.2,2004.11,2004.11.1,2004.11.2,2004.12,2004.12.1,2004.12.2,2005.01,2005.01.1,2005.01.2,2005.02,2005.02.1,2005.02.2,2005.03,2005.03.1,2005.03.2,2005.04,2005.04.1,2005.04.2,2005.05,2005.05.1,2005.05.2,2005.06,2005.06.1,2005.06.2,2005.07,2005.07.1,2005.07.2,2005.08,2005.08.1,2005.08.2,2005.09,2005.09.1,2005.09.2,2005.10,2005.10.1,2005.10.2,2005.11,2005.11.1,2005.11.2,2005.12,2005.12.1,2005.12.2,2006.01,2006.01.1,2006.01.2,2006.02,2006.02.1,2006.02.2,2006.03,2006.03.1,2006.03.2,2006.04,2006.04.1,2006.04.2,2006.05,2006.05.1,2006.05.2,2006.06,2006.06.1,2006.06.2,2006.07,2006.07.1,2006.07.2,2006.08,2006.08.1,2006.08.2,2006.09,2006.09.1,2006.09.2,2006.10,2006.10.1,2006.10.2,2006.11,2006.11.1,2006.11.2,2006.12,2006.12.1,2006.12.2,2007.01,2007.01.1,2007.01.2,2007.02,2007.02.1,2007.02.2,2007.03,2007.03.1,2007.03.2,2007.04,2007.04.1,2007.04.2,2007.05,2007.05.1,2007.05.2,2007.06,2007.06.1,2007.06.2,2007.07,2007.07.1,2007.07.2,2007.08,2007.08.1,2007.08.2,2007.09,2007.09.1,2007.09.2,2007.10,2007.10.1,2007.10.2,2007.11,2007.11.1,2007.11.2,2007.12,2007.12.1,2007.12.2,2008.01,2008.01.1,2008.01.2,2008.02,2008.02.1,2008.02.2,2008.03,2008.03.1,2008.03.2,2008.04,2008.04.1,2008.04.2,2008.05,2008.05.1,2008.05.2,2008.06,2008.06.1,...,2015.11,2015.11.1,2015.11.2,2015.12,2015.12.1,2015.12.2,2016.01,2016.01.1,2016.01.2,2016.02,2016.02.1,2016.02.2,2016.03,2016.03.1,2016.03.2,2016.04,2016.04.1,2016.04.2,2016.05,2016.05.1,2016.05.2,2016.06,2016.06.1,2016.06.2,2016.07,2016.07.1,2016.07.2,2016.08,2016.08.1,2016.08.2,2016.09,2016.09.1,2016.09.2,2016.10,2016.10.1,2016.10.2,2016.11,2016.11.1,2016.11.2,2016.12,2016.12.1,2016.12.2,2017.01,2017.01.1,2017.01.2,2017.02,2017.02.1,2017.02.2,2017.03,2017.03.1,2017.03.2,2017.04,2017.04.1,2017.04.2,2017.05,2017.05.1,2017.05.2,2017.06,2017.06.1,2017.06.2,2017.07,2017.07.1,2017.07.2,2017.08,2017.08.1,2017.08.2,2017.09,2017.09.1,2017.09.2,2017.10,2017.10.1,2017.10.2,2017.11,2017.11.1,2017.11.2,2017.12,2017.12.1,2017.12.2,2018.01,2018.01.1,2018.01.2,2018.02,2018.02.1,2018.02.2,2018.03,2018.03.1,2018.03.2,2018.04,2018.04.1,2018.04.2,2018.05,2018.05.1,2018.05.2,2018.06,2018.06.1,2018.06.2,2018.07,2018.07.1,2018.07.2,2018.08,2018.08.1,2018.08.2,2018.09,2018.09.1,2018.09.2,2018.10,2018.10.1,2018.10.2,2018.11,2018.11.1,2018.11.2,2018.12,2018.12.1,2018.12.2,2019.01,2019.01.1,2019.01.2,2019.02,2019.02.1,2019.02.2,2019.03,2019.03.1,2019.03.2,2019.04,2019.04.1,2019.04.2,2019.05,2019.05.1,2019.05.2,2019.06,2019.06.1,2019.06.2,2019.07,2019.07.1,2019.07.2,2019.08,2019.08.1,2019.08.2,2019.09,2019.09.1,2019.09.2,2019.10,2019.10.1,2019.10.2,2019.11,2019.11.1,2019.11.2,2019.12,2019.12.1,2019.12.2,2020.01,2020.01.1,2020.01.2,2020.02,2020.02.1,2020.02.2,2020.03,2020.03.1,2020.03.2,2020.04,2020.04.1,2020.04.2,2020.05,2020.05.1,2020.05.2,2020.06,2020.06.1,2020.06.2,2020.07,2020.07.1,2020.07.2,2020.08,2020.08.1,2020.08.2,2020.09,2020.09.1,2020.09.2,2020.10,2020.10.1,2020.10.2,2020.11,2020.11.1,2020.11.2,2020.12,2020.12.1,2020.12.2,2021.01,2021.01.1,2021.01.2,2021.02,2021.02.1,2021.02.2,2021.03,2021.03.1,2021.03.2,2021.04,2021.04.1,2021.04.2,2021.05,2021.05.1,2021.05.2,2021.06,2021.06.1,2021.06.2,2021.07,2021.07.1,2021.07.2,2021.08,2021.08.1,2021.08.2,2021.09,2021.09.1,2021.09.2,2021.10,2021.10.1,2021.10.2,2021.11,2021.11.1,2021.11.2,2021.12,2021.12.1,2021.12.2,2022.01,2022.01.1,2022.01.2,2022.02,2022.02.1,2022.02.2,2022.03,2022.03.1,2022.03.2,2022.04,2022.04.1,2022.04.2,2022.05,2022.05.1,2022.05.2,2022.06,2022.06.1,2022.06.2,2022.07,2022.07.1,2022.07.2,2022.08,2022.08.1,2022.08.2,2022.09,2022.09.1,2022.09.2,2022.10,2022.10.1,2022.10.2,2022.11,2022.11.1,2022.11.2,2022.12,2022.12.1,2022.12.2,2023.01,2023.01.1,2023.01.2,2023.02,2023.02.1,2023.02.2,2023.03,2023.03.1,2023.03.2,2023.04,2023.04.1,2023.04.2,2023.05,2023.05.1,2023.05.2,2023.06,2023.06.1,2023.06.2,2023.07,2023.07.1,2023.07.2,2023.08,2023.08.1,2023.08.2,2023.09,2023.09.1,2023.09.2,2023.10,2023.10.1,2023.10.2,2023.11,2023.11.1,2023.11.2,2023.12,2023.12.1,2023.12.2,2024.01,2024.01.1,2024.01.2,2024.02,2024.02.1,2024.02.2,2024.03,2024.03.1,2024.03.2,2024.04,2024.04.1,2024.04.2,2024.05,2024.05.1,2024.05.2,2024.06,2024.06.1,2024.06.2,2024.07,2024.07.1,2024.07.2,2024.08,2024.08.1,2024.08.2,2024.09,2024.09.1,2024.09.2,2024.10,2024.10.1,2024.10.2,2024.11,2024.11.1,2024.11.2,2024.12,2024.12.1,2024.12.2,1997,1997.1,1997.2,1998,1998.1,1998.2,1999,1999.1,1999.2,2000,2000.1,2000.2,2001,2001.1,2001.2,2002,2002.1,2002.2,2003,2003.1,2003.2,2004,2004.1,2004.2,2005,2005.1,2005.2,2006,2006.1,2006.2,2007,2007.1,2007.2,2008,2008.1,2008.2,2009,2009.1,2009.2,2010,2010.1,2010.2,2011,2011.1,2011.2,2012,2012.1,2012.2,2013,2013.1,2013.2,2014,2014.1,2014.2,2015,2015.1,2015.2,2016,2016.1,2016.2,2017,2017.1,2017.2,2018,2018.1,2018.2,2019,2019.1,2019.2,2020,2020.1,2020.2,2021,2021.1,2021.2,2022,2022.1,2022.2,2023,2023.1,2023.2,2024,2024.1,2024.2
0,시군구별,계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),...,계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명)
1,전국,63268,33266,30002,58144,30086,28058,62160,32333,29827,56949,29449,27500,55270,28830,26440,50978,26713,24265,53369,27704,25665,53254,27623,25631,55461,28907,26554,57136,29576,27560,53848,28036,25812,55557,28406,27151,60347,31603,28744,56841,29806,27035,60238,31421,28817,54814,28605,26209,52046,27375,24671,49571,25938,23633,50151,26306,23845,49634,26030,23604,53484,27963,25521,52709,27580,25129,50164,26413,23751,51595,27107,24488,58607,30600,28007,53305,27728,25577,57495,29946,27549,52386,27648,24738,50516,26544,23972,46765,24639,22126,48780,25496,23284,48502,25512,22990,51056,26778,24278,52224,27239,24985,50559,26141,24418,50473,26138,24335,61644,32317,29327,56723,29693,27030,59878,31432,28446,53058,27986,25072,52492,27578,24914,46774,24435,22339,48377,25322,23055,50623,26579,24044,52913,27692,25221,54429,28273,26156,52403,27406,24997,50775,26720,24055,56949,29736,27213,49939,25873,24066,54549,28388,26161,48309,25458,22851,46802,24260,22542,41809,21949,19860,42404,22142,20262,43830,22903,20927,45673,23912,21761,44814,23391,21423,42753,22361,20392,42103,21616,20487,48825,25851,22974,43579,22559,21020,47753,24859,22894,43453,22765,20688,41977,22054,19923,37575,19888,17687,40361,21274,19087,39751,20861,18890,39615,20727,18888,39458,20432,19026,37921,19617,18304,36643,19341,17302,45423,23615,21808,41909,21653,20256,45972,23869,22103,43040,22318,20722,41132,21523,19609,36879,19398,17481,38008,19820,18188,38054,19882,18172,41645,21861,19784,43345,22451,20894,40752,21243,19509,38877,20094,18783,45778,23824,21954,41059,21310,19749,45422,23611,21811,40611,21057,19554,38933,20258,18675,36086,18778,17308,38031,19949,18082,38324,19952,18372,39238,20427,18811,40855,21238,19617,37432,19248,18184,35189,18183,17006,41354,21438,19916,35810,18362,17448,41052,21242,19810,36605,18929,17676,35983,18833,17150,33725,17466,16259,34658,18237,16421,36003,18774,17229,37413,19267,18146,37283,19243,18040,35737,18585,17152,33084,17216,15868,40692,21010,19682,37522,19319,18203,41209,21481,19728,37666,19466,18200,37740,19564,18176,35347,18364,16983,35154,18308,16846,37457,19473,17984,38471,20015,18456,38556,19867,18689,37110,19238,17872,34835,18005,16830,43704,22585,21119,39485,20361,19124,43578,22234,21344,40290,20696,19594,39913,20593,19320,37112,19170,17942,39522,20545,18977,44041,22486,21555,44871,23290,21581,45722,23499,22223,41865,21487,20378,36719,18926,17793,46747,24046,22701,39495,20298,19197,41318,21386,19932,38783,20090,18693,37598,19459,18139,35035,17998,...,33467,17143,16324,31910,16205,15705,39405,20237,19168,34830,17766,17064,38131,19471,18660,35147,17910,17237,34341,17588,16753,32849,16863,15986,33920,17482,16438,33897,17312,16585,34375,17675,16700,31592,16180,15412,30366,15476,14890,27390,14104,13286,34834,17844,16990,30499,15643,14856,33196,17129,16067,30337,15688,14649,30303,15581,14722,28892,14912,13980,29418,15243,14175,30135,15449,14686,30085,15511,14574,27857,14297,13560,27068,14036,13032,25147,12975,12172,32198,16471,15727,27575,14083,13492,29987,15376,14611,27734,14226,13508,27949,14371,13578,26357,13464,12893,27033,13787,13246,27381,14098,13283,26066,13509,12557,26474,13601,12873,25301,13014,12287,22767,11686,11081,30271,15545,14726,25710,13073,12637,27049,13975,13074,26104,13441,12663,25299,12957,12342,23992,12363,11629,25222,12974,12248,24371,12491,11880,24090,12488,11602,25613,12989,12624,23727,12097,11630,21228,11023,10205,26646,13622,13024,22759,11602,11157,24190,12423,11767,23299,11906,11393,22847,11825,11022,22117,11240,10877,22999,11771,11228,22402,11526,10876,23499,11947,11552,21884,11172,10712,20054,10300,9754,19641,10028,9613,24894,12756,12138,21306,11013,10293,23925,12280,11645,22703,11594,11109,21922,11168,10754,21504,11173,10331,22364,11411,10953,22282,11435,10847,21905,11162,10743,20749,10598,10151,19829,10201,9628,17179,8725,8454,24637,12388,12249,20702,10680,10022,23000,11772,11228,21164,10780,10384,20070,10266,9804,18915,9709,9206,20475,10470,10005,21782,11235,10547,21918,11203,10715,20646,10530,10116,18981,9737,9244,16896,8684,8212,23198,11814,11384,20012,10351,9661,21193,10900,10293,18515,9461,9054,19047,9767,9280,18585,9514,9071,19085,9742,9343,18974,9854,9120,18706,9611,9095,18878,9566,9312,17530,8951,8579,16305,8331,7974,21412,11001,10411,19375,9975,9400,19671,10064,9607,19037,9723,9314,19541,10009,9532,18244,9215,9029,20580,10602,9978,20103,10272,9831,20589,10542,10047,21426,10920,10506,20083,10310,9773,18256,9414,8842,675394,350929,324465,641594,336147,305447,620668,324409,296259,640089,335433,304656,559934,291989,267945,496911,260228,236683,495036,257727,237309,476958,247835,229123,438707,227592,211115,451759,234110,217649,496822,255872,240950,465892,240119,225773,444849,229351,215498,470171,242901,227270,471265,242121,229144,484550,248958,235592,436455,223883,212572,435435,223356,212079,438420,224906,213514,406243,208064,198179,357771,184308,173463,326822,167686,159136,302676,155416,147260,272337,139362,132975,260562,133516,127046,249186,127454,121732,230028,117862,112166,238317,122047,116270

In [5]:
df_kosis = pd.read_csv('./source/시군구_성_월별_출생_202607.csv', encoding='utf-8')
df_kosis.head()

,시군구별,1997.01,1997.01.1,1997.01.2,1997.02,1997.02.1,1997.02.2,1997.03,1997.03.1,1997.03.2,1997.04,1997.04.1,1997.04.2,1997.05,1997.05.1,1997.05.2,1997.06,1997.06.1,1997.06.2,1997.07,1997.07.1,1997.07.2,1997.08,1997.08.1,1997.08.2,1997.09,1997.09.1,1997.09.2,1997.10,1997.10.1,1997.10.2,1997.11,1997.11.1,1997.11.2,1997.12,1997.12.1,1997.12.2,1998.01,1998.01.1,1998.01.2,1998.02,1998.02.1,1998.02.2,1998.03,1998.03.1,1998.03.2,1998.04,1998.04.1,1998.04.2,1998.05,1998.05.1,1998.05.2,1998.06,1998.06.1,1998.06.2,1998.07,1998.07.1,1998.07.2,1998.08,1998.08.1,1998.08.2,1998.09,1998.09.1,1998.09.2,1998.10,1998.10.1,1998.10.2,1998.11,1998.11.1,1998.11.2,1998.12,1998.12.1,1998.12.2,1999.01,1999.01.1,1999.01.2,1999.02,1999.02.1,1999.02.2,1999.03,1999.03.1,1999.03.2,1999.04,1999.04.1,1999.04.2,1999.05,1999.05.1,1999.05.2,1999.06,1999.06.1,1999.06.2,1999.07,1999.07.1,1999.07.2,1999.08,1999.08.1,1999.08.2,1999.09,1999.09.1,1999.09.2,1999.10,1999.10.1,1999.10.2,1999.11,1999.11.1,1999.11.2,1999.12,1999.12.1,1999.12.2,2000.01,2000.01.1,2000.01.2,2000.02,2000.02.1,2000.02.2,2000.03,2000.03.1,2000.03.2,2000.04,2000.04.1,2000.04.2,2000.05,2000.05.1,2000.05.2,2000.06,2000.06.1,2000.06.2,2000.07,2000.07.1,2000.07.2,2000.08,2000.08.1,2000.08.2,2000.09,2000.09.1,2000.09.2,2000.10,2000.10.1,2000.10.2,2000.11,2000.11.1,2000.11.2,2000.12,2000.12.1,2000.12.2,2001.01,2001.01.1,2001.01.2,2001.02,2001.02.1,2001.02.2,2001.03,2001.03.1,2001.03.2,2001.04,2001.04.1,2001.04.2,2001.05,2001.05.1,2001.05.2,2001.06,2001.06.1,2001.06.2,2001.07,2001.07.1,2001.07.2,2001.08,2001.08.1,2001.08.2,2001.09,2001.09.1,2001.09.2,2001.10,2001.10.1,2001.10.2,2001.11,2001.11.1,2001.11.2,2001.12,2001.12.1,2001.12.2,2002.01,2002.01.1,2002.01.2,2002.02,2002.02.1,2002.02.2,2002.03,2002.03.1,2002.03.2,2002.04,2002.04.1,2002.04.2,2002.05,2002.05.1,2002.05.2,2002.06,2002.06.1,2002.06.2,2002.07,2002.07.1,2002.07.2,2002.08,2002.08.1,2002.08.2,2002.09,2002.09.1,2002.09.2,2002.10,2002.10.1,2002.10.2,2002.11,2002.11.1,2002.11.2,2002.12,2002.12.1,2002.12.2,2003.01,2003.01.1,2003.01.2,2003.02,2003.02.1,2003.02.2,2003.03,2003.03.1,2003.03.2,2003.04,2003.04.1,2003.04.2,2003.05,2003.05.1,2003.05.2,2003.06,2003.06.1,2003.06.2,2003.07,2003.07.1,2003.07.2,2003.08,2003.08.1,2003.08.2,2003.09,2003.09.1,2003.09.2,2003.10,2003.10.1,2003.10.2,2003.11,2003.11.1,2003.11.2,2003.12,2003.12.1,2003.12.2,2004.01,2004.01.1,2004.01.2,2004.02,2004.02.1,2004.02.2,2004.03,2004.03.1,2004.03.2,2004.04,2004.04.1,2004.04.2,2004.05,2004.05.1,2004.05.2,2004.06,2004.06.1,2004.06.2,2004.07,2004.07.1,2004.07.2,2004.08,2004.08.1,2004.08.2,2004.09,2004.09.1,2004.09.2,2004.10,2004.10.1,2004.10.2,2004.11,2004.11.1,2004.11.2,2004.12,2004.12.1,2004.12.2,2005.01,2005.01.1,2005.01.2,2005.02,2005.02.1,2005.02.2,2005.03,2005.03.1,2005.03.2,2005.04,2005.04.1,2005.04.2,2005.05,2005.05.1,2005.05.2,2005.06,2005.06.1,2005.06.2,2005.07,2005.07.1,2005.07.2,2005.08,2005.08.1,2005.08.2,2005.09,2005.09.1,2005.09.2,2005.10,2005.10.1,2005.10.2,2005.11,2005.11.1,2005.11.2,2005.12,2005.12.1,2005.12.2,2006.01,2006.01.1,2006.01.2,2006.02,2006.02.1,2006.02.2,2006.03,2006.03.1,2006.03.2,2006.04,2006.04.1,2006.04.2,2006.05,2006.05.1,2006.05.2,2006.06,2006.06.1,2006.06.2,2006.07,2006.07.1,2006.07.2,2006.08,2006.08.1,2006.08.2,2006.09,2006.09.1,2006.09.2,2006.10,2006.10.1,2006.10.2,2006.11,2006.11.1,2006.11.2,2006.12,2006.12.1,2006.12.2,2007.01,2007.01.1,2007.01.2,2007.02,2007.02.1,2007.02.2,2007.03,2007.03.1,2007.03.2,2007.04,2007.04.1,2007.04.2,2007.05,2007.05.1,2007.05.2,2007.06,2007.06.1,2007.06.2,2007.07,2007.07.1,2007.07.2,2007.08,2007.08.1,2007.08.2,2007.09,2007.09.1,2007.09.2,2007.10,2007.10.1,2007.10.2,2007.11,2007.11.1,2007.11.2,2007.12,2007.12.1,2007.12.2,2008.01,2008.01.1,2008.01.2,2008.02,2008.02.1,2008.02.2,2008.03,2008.03.1,2008.03.2,2008.04,2008.04.1,2008.04.2,2008.05,2008.05.1,2008.05.2,2008.06,2008.06.1,...,2015.11,2015.11.1,2015.11.2,2015.12,2015.12.1,2015.12.2,2016.01,2016.01.1,2016.01.2,2016.02,2016.02.1,2016.02.2,2016.03,2016.03.1,2016.03.2,2016.04,2016.04.1,2016.04.2,2016.05,2016.05.1,2016.05.2,2016.06,2016.06.1,2016.06.2,2016.07,2016.07.1,2016.07.2,2016.08,2016.08.1,2016.08.2,2016.09,2016.09.1,2016.09.2,2016.10,2016.10.1,2016.10.2,2016.11,2016.11.1,2016.11.2,2016.12,2016.12.1,2016.12.2,2017.01,2017.01.1,2017.01.2,2017.02,2017.02.1,2017.02.2,2017.03,2017.03.1,2017.03.2,2017.04,2017.04.1,2017.04.2,2017.05,2017.05.1,2017.05.2,2017.06,2017.06.1,2017.06.2,2017.07,2017.07.1,2017.07.2,2017.08,2017.08.1,2017.08.2,2017.09,2017.09.1,2017.09.2,2017.10,2017.10.1,2017.10.2,2017.11,2017.11.1,2017.11.2,2017.12,2017.12.1,2017.12.2,2018.01,2018.01.1,2018.01.2,2018.02,2018.02.1,2018.02.2,2018.03,2018.03.1,2018.03.2,2018.04,2018.04.1,2018.04.2,2018.05,2018.05.1,2018.05.2,2018.06,2018.06.1,2018.06.2,2018.07,2018.07.1,2018.07.2,2018.08,2018.08.1,2018.08.2,2018.09,2018.09.1,2018.09.2,2018.10,2018.10.1,2018.10.2,2018.11,2018.11.1,2018.11.2,2018.12,2018.12.1,2018.12.2,2019.01,2019.01.1,2019.01.2,2019.02,2019.02.1,2019.02.2,2019.03,2019.03.1,2019.03.2,2019.04,2019.04.1,2019.04.2,2019.05,2019.05.1,2019.05.2,2019.06,2019.06.1,2019.06.2,2019.07,2019.07.1,2019.07.2,2019.08,2019.08.1,2019.08.2,2019.09,2019.09.1,2019.09.2,2019.10,2019.10.1,2019.10.2,2019.11,2019.11.1,2019.11.2,2019.12,2019.12.1,2019.12.2,2020.01,2020.01.1,2020.01.2,2020.02,2020.02.1,2020.02.2,2020.03,2020.03.1,2020.03.2,2020.04,2020.04.1,2020.04.2,2020.05,2020.05.1,2020.05.2,2020.06,2020.06.1,2020.06.2,2020.07,2020.07.1,2020.07.2,2020.08,2020.08.1,2020.08.2,2020.09,2020.09.1,2020.09.2,2020.10,2020.10.1,2020.10.2,2020.11,2020.11.1,2020.11.2,2020.12,2020.12.1,2020.12.2,2021.01,2021.01.1,2021.01.2,2021.02,2021.02.1,2021.02.2,2021.03,2021.03.1,2021.03.2,2021.04,2021.04.1,2021.04.2,2021.05,2021.05.1,2021.05.2,2021.06,2021.06.1,2021.06.2,2021.07,2021.07.1,2021.07.2,2021.08,2021.08.1,2021.08.2,2021.09,2021.09.1,2021.09.2,2021.10,2021.10.1,2021.10.2,2021.11,2021.11.1,2021.11.2,2021.12,2021.12.1,2021.12.2,2022.01,2022.01.1,2022.01.2,2022.02,2022.02.1,2022.02.2,2022.03,2022.03.1,2022.03.2,2022.04,2022.04.1,2022.04.2,2022.05,2022.05.1,2022.05.2,2022.06,2022.06.1,2022.06.2,2022.07,2022.07.1,2022.07.2,2022.08,2022.08.1,2022.08.2,2022.09,2022.09.1,2022.09.2,2022.10,2022.10.1,2022.10.2,2022.11,2022.11.1,2022.11.2,2022.12,2022.12.1,2022.12.2,2023.01,2023.01.1,2023.01.2,2023.02,2023.02.1,2023.02.2,2023.03,2023.03.1,2023.03.2,2023.04,2023.04.1,2023.04.2,2023.05,2023.05.1,2023.05.2,2023.06,2023.06.1,2023.06.2,2023.07,2023.07.1,2023.07.2,2023.08,2023.08.1,2023.08.2,2023.09,2023.09.1,2023.09.2,2023.10,2023.10.1,2023.10.2,2023.11,2023.11.1,2023.11.2,2023.12,2023.12.1,2023.12.2,2024.01,2024.01.1,2024.01.2,2024.02,2024.02.1,2024.02.2,2024.03,2024.03.1,2024.03.2,2024.04,2024.04.1,2024.04.2,2024.05,2024.05.1,2024.05.2,2024.06,2024.06.1,2024.06.2,2024.07,2024.07.1,2024.07.2,2024.08,2024.08.1,2024.08.2,2024.09,2024.09.1,2024.09.2,2024.10,2024.10.1,2024.10.2,2024.11,2024.11.1,2024.11.2,2024.12,2024.12.1,2024.12.2,1997,1997.1,1997.2,1998,1998.1,1998.2,1999,1999.1,1999.2,2000,2000.1,2000.2,2001,2001.1,2001.2,2002,2002.1,2002.2,2003,2003.1,2003.2,2004,2004.1,2004.2,2005,2005.1,2005.2,2006,2006.1,2006.2,2007,2007.1,2007.2,2008,2008.1,2008.2,2009,2009.1,2009.2,2010,2010.1,2010.2,2011,2011.1,2011.2,2012,2012.1,2012.2,2013,2013.1,2013.2,2014,2014.1,2014.2,2015,2015.1,2015.2,2016,2016.1,2016.2,2017,2017.1,2017.2,2018,2018.1,2018.2,2019,2019.1,2019.2,2020,2020.1,2020.2,2021,2021.1,2021.2,2022,2022.1,2022.2,2023,2023.1,2023.2,2024,2024.1,2024.2
0,시군구별,계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),...,계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명),계 (명),남자 (명),여자 (명)
1,전국,63268,33266,30002,58144,30086,28058,62160,32333,29827,56949,29449,27500,55270,28830,26440,50978,26713,24265,53369,27704,25665,53254,27623,25631,55461,28907,26554,57136,29576,27560,53848,28036,25812,55557,28406,27151,60347,31603,28744,56841,29806,27035,60238,31421,28817,54814,28605,26209,52046,27375,24671,49571,25938,23633,50151,26306,23845,49634,26030,23604,53484,27963,25521,52709,27580,25129,50164,26413,23751,51595,27107,24488,58607,30600,28007,53305,27728,25577,57495,29946,27549,52386,27648,24738,50516,26544,23972,46765,24639,22126,48780,25496,23284,48502,25512,22990,51056,26778,24278,52224,27239,24985,50559,26141,24418,50473,26138,24335,61644,32317,29327,56723,29693,27030,59878,31432,28446,53058,27986,25072,52492,27578,24914,46774,24435,22339,48377,25322,23055,50623,26579,24044,52913,27692,25221,54429,28273,26156,52403,27406,24997,50775,26720,24055,56949,29736,27213,49939,25873,24066,54549,28388,26161,48309,25458,22851,46802,24260,22542,41809,21949,19860,42404,22142,20262,43830,22903,20927,45673,23912,21761,44814,23391,21423,42753,22361,20392,42103,21616,20487,48825,25851,22974,43579,22559,21020,47753,24859,22894,43453,22765,20688,41977,22054,19923,37575,19888,17687,40361,21274,19087,39751,20861,18890,39615,20727,18888,39458,20432,19026,37921,19617,18304,36643,19341,17302,45423,23615,21808,41909,21653,20256,45972,23869,22103,43040,22318,20722,41132,21523,19609,36879,19398,17481,38008,19820,18188,38054,19882,18172,41645,21861,19784,43345,22451,20894,40752,21243,19509,38877,20094,18783,45778,23824,21954,41059,21310,19749,45422,23611,21811,40611,21057,19554,38933,20258,18675,36086,18778,17308,38031,19949,18082,38324,19952,18372,39238,20427,18811,40855,21238,19617,37432,19248,18184,35189,18183,17006,41354,21438,19916,35810,18362,17448,41052,21242,19810,36605,18929,17676,35983,18833,17150,33725,17466,16259,34658,18237,16421,36003,18774,17229,37413,19267,18146,37283,19243,18040,35737,18585,17152,33084,17216,15868,40692,21010,19682,37522,19319,18203,41209,21481,19728,37666,19466,18200,37740,19564,18176,35347,18364,16983,35154,18308,16846,37457,19473,17984,38471,20015,18456,38556,19867,18689,37110,19238,17872,34835,18005,16830,43704,22585,21119,39485,20361,19124,43578,22234,21344,40290,20696,19594,39913,20593,19320,37112,19170,17942,39522,20545,18977,44041,22486,21555,44871,23290,21581,45722,23499,22223,41865,21487,20378,36719,18926,17793,46747,24046,22701,39495,20298,19197,41318,21386,19932,38783,20090,18693,37598,19459,18139,35035,17998,...,33467,17143,16324,31910,16205,15705,39405,20237,19168,34830,17766,17064,38131,19471,18660,35147,17910,17237,34341,17588,16753,32849,16863,15986,33920,17482,16438,33897,17312,16585,34375,17675,16700,31592,16180,15412,30366,15476,14890,27390,14104,13286,34834,17844,16990,30499,15643,14856,33196,17129,16067,30337,15688,14649,30303,15581,14722,28892,14912,13980,29418,15243,14175,30135,15449,14686,30085,15511,14574,27857,14297,13560,27068,14036,13032,25147,12975,12172,32198,16471,15727,27575,14083,13492,29987,15376,14611,27734,14226,13508,27949,14371,13578,26357,13464,12893,27033,13787,13246,27381,14098,13283,26066,13509,12557,26474,13601,12873,25301,13014,12287,22767,11686,11081,30271,15545,14726,25710,13073,12637,27049,13975,13074,26104,13441,12663,25299,12957,12342,23992,12363,11629,25222,12974,12248,24371,12491,11880,24090,12488,11602,25613,12989,12624,23727,12097,11630,21228,11023,10205,26646,13622,13024,22759,11602,11157,24190,12423,11767,23299,11906,11393,22847,11825,11022,22117,11240,10877,22999,11771,11228,22402,11526,10876,23499,11947,11552,21884,11172,10712,20054,10300,9754,19641,10028,9613,24894,12756,12138,21306,11013,10293,23925,12280,11645,22703,11594,11109,21922,11168,10754,21504,11173,10331,22364,11411,10953,22282,11435,10847,21905,11162,10743,20749,10598,10151,19829,10201,9628,17179,8725,8454,24637,12388,12249,20702,10680,10022,23000,11772,11228,21164,10780,10384,20070,10266,9804,18915,9709,9206,20475,10470,10005,21782,11235,10547,21918,11203,10715,20646,10530,10116,18981,9737,9244,16896,8684,8212,23198,11814,11384,20012,10351,9661,21193,10900,10293,18515,9461,9054,19047,9767,9280,18585,9514,9071,19085,9742,9343,18974,9854,9120,18706,9611,9095,18878,9566,9312,17530,8951,8579,16305,8331,7974,21412,11001,10411,19375,9975,9400,19671,10064,9607,19037,9723,9314,19541,10009,9532,18244,9215,9029,20580,10602,9978,20103,10272,9831,20589,10542,10047,21426,10920,10506,20083,10310,9773,18256,9414,8842,675394,350929,324465,641594,336147,305447,620668,324409,296259,640089,335433,304656,559934,291989,267945,496911,260228,236683,495036,257727,237309,476958,247835,229123,438707,227592,211115,451759,234110,217649,496822,255872,240950,465892,240119,225773,444849,229351,215498,470171,242901,227270,471265,242121,229144,484550,248958,235592,436455,223883,212572,435435,223356,212079,438420,224906,213514,406243,208064,198179,357771,184308,173463,326822,167686,159136,302676,155416,147260,272337,139362,132975,260562,133516,127046,249186,127454,121732,230028,117862,112166,238317,122047,116270

In [6]:
df_kosis.tail()

,시군구별,1997.01,1997.01.1,1997.01.2,1997.02,1997.02.1,1997.02.2,1997.03,1997.03.1,1997.03.2,1997.04,1997.04.1,1997.04.2,1997.05,1997.05.1,1997.05.2,1997.06,1997.06.1,1997.06.2,1997.07,1997.07.1,1997.07.2,1997.08,1997.08.1,1997.08.2,1997.09,1997.09.1,1997.09.2,1997.10,1997.10.1,1997.10.2,1997.11,1997.11.1,1997.11.2,1997.12,1997.12.1,1997.12.2,1998.01,1998.01.1,1998.01.2,1998.02,1998.02.1,1998.02.2,1998.03,1998.03.1,1998.03.2,1998.04,1998.04.1,1998.04.2,1998.05,1998.05.1,1998.05.2,1998.06,1998.06.1,1998.06.2,1998.07,1998.07.1,1998.07.2,1998.08,1998.08.1,1998.08.2,1998.09,1998.09.1,1998.09.2,1998.10,1998.10.1,1998.10.2,1998.11,1998.11.1,1998.11.2,1998.12,1998.12.1,1998.12.2,1999.01,1999.01.1,1999.01.2,1999.02,1999.02.1,1999.02.2,1999.03,1999.03.1,1999.03.2,1999.04,1999.04.1,1999.04.2,1999.05,1999.05.1,1999.05.2,1999.06,1999.06.1,1999.06.2,1999.07,1999.07.1,1999.07.2,1999.08,1999.08.1,1999.08.2,1999.09,1999.09.1,1999.09.2,1999.10,1999.10.1,1999.10.2,1999.11,1999.11.1,1999.11.2,1999.12,1999.12.1,1999.12.2,2000.01,2000.01.1,2000.01.2,2000.02,2000.02.1,2000.02.2,2000.03,2000.03.1,2000.03.2,2000.04,2000.04.1,2000.04.2,2000.05,2000.05.1,2000.05.2,2000.06,2000.06.1,2000.06.2,2000.07,2000.07.1,2000.07.2,2000.08,2000.08.1,2000.08.2,2000.09,2000.09.1,2000.09.2,2000.10,2000.10.1,2000.10.2,2000.11,2000.11.1,2000.11.2,2000.12,2000.12.1,2000.12.2,2001.01,2001.01.1,2001.01.2,2001.02,2001.02.1,2001.02.2,2001.03,2001.03.1,2001.03.2,2001.04,2001.04.1,2001.04.2,2001.05,2001.05.1,2001.05.2,2001.06,2001.06.1,2001.06.2,2001.07,2001.07.1,2001.07.2,2001.08,2001.08.1,2001.08.2,2001.09,2001.09.1,2001.09.2,2001.10,2001.10.1,2001.10.2,2001.11,2001.11.1,2001.11.2,2001.12,2001.12.1,2001.12.2,2002.01,2002.01.1,2002.01.2,2002.02,2002.02.1,2002.02.2,2002.03,2002.03.1,2002.03.2,2002.04,2002.04.1,2002.04.2,2002.05,2002.05.1,2002.05.2,2002.06,2002.06.1,2002.06.2,2002.07,2002.07.1,2002.07.2,2002.08,2002.08.1,2002.08.2,2002.09,2002.09.1,2002.09.2,2002.10,2002.10.1,2002.10.2,2002.11,2002.11.1,2002.11.2,2002.12,2002.12.1,2002.12.2,2003.01,2003.01.1,2003.01.2,2003.02,2003.02.1,2003.02.2,2003.03,2003.03.1,2003.03.2,2003.04,2003.04.1,2003.04.2,2003.05,2003.05.1,2003.05.2,2003.06,2003.06.1,2003.06.2,2003.07,2003.07.1,2003.07.2,2003.08,2003.08.1,2003.08.2,2003.09,2003.09.1,2003.09.2,2003.10,2003.10.1,2003.10.2,2003.11,2003.11.1,2003.11.2,2003.12,2003.12.1,2003.12.2,2004.01,2004.01.1,2004.01.2,2004.02,2004.02.1,2004.02.2,2004.03,2004.03.1,2004.03.2,2004.04,2004.04.1,2004.04.2,2004.05,2004.05.1,2004.05.2,2004.06,2004.06.1,2004.06.2,2004.07,2004.07.1,2004.07.2,2004.08,2004.08.1,2004.08.2,2004.09,2004.09.1,2004.09.2,2004.10,2004.10.1,2004.10.2,2004.11,2004.11.1,2004.11.2,2004.12,2004.12.1,2004.12.2,2005.01,2005.01.1,2005.01.2,2005.02,2005.02.1,2005.02.2,2005.03,2005.03.1,2005.03.2,2005.04,2005.04.1,2005.04.2,2005.05,2005.05.1,2005.05.2,2005.06,2005.06.1,2005.06.2,2005.07,2005.07.1,2005.07.2,2005.08,2005.08.1,2005.08.2,2005.09,2005.09.1,2005.09.2,2005.10,2005.10.1,2005.10.2,2005.11,2005.11.1,2005.11.2,2005.12,2005.12.1,2005.12.2,2006.01,2006.01.1,2006.01.2,2006.02,2006.02.1,2006.02.2,2006.03,2006.03.1,2006.03.2,2006.04,2006.04.1,2006.04.2,2006.05,2006.05.1,2006.05.2,2006.06,2006.06.1,2006.06.2,2006.07,2006.07.1,2006.07.2,2006.08,2006.08.1,2006.08.2,2006.09,2006.09.1,2006.09.2,2006.10,2006.10.1,2006.10.2,2006.11,2006.11.1,2006.11.2,2006.12,2006.12.1,2006.12.2,2007.01,2007.01.1,2007.01.2,2007.02,2007.02.1,2007.02.2,2007.03,2007.03.1,2007.03.2,2007.04,2007.04.1,2007.04.2,2007.05,2007.05.1,2007.05.2,2007.06,2007.06.1,2007.06.2,2007.07,2007.07.1,2007.07.2,2007.08,2007.08.1,2007.08.2,2007.09,2007.09.1,2007.09.2,2007.10,2007.10.1,2007.10.2,2007.11,2007.11.1,2007.11.2,2007.12,2007.12.1,2007.12.2,2008.01,2008.01.1,2008.01.2,2008.02,2008.02.1,2008.02.2,2008.03,2008.03.1,2008.03.2,2008.04,2008.04.1,2008.04.2,2008.05,2008.05.1,2008.05.2,2008.06,2008.06.1,...,2015.11,2015.11.1,2015.11.2,2015.12,2015.12.1,2015.12.2,2016.01,2016.01.1,2016.01.2,2016.02,2016.02.1,2016.02.2,2016.03,2016.03.1,2016.03.2,2016.04,2016.04.1,2016.04.2,2016.05,2016.05.1,2016.05.2,2016.06,2016.06.1,2016.06.2,2016.07,2016.07.1,2016.07.2,2016.08,2016.08.1,2016.08.2,2016.09,2016.09.1,2016.09.2,2016.10,2016.10.1,2016.10.2,2016.11,2016.11.1,2016.11.2,2016.12,2016.12.1,2016.12.2,2017.01,2017.01.1,2017.01.2,2017.02,2017.02.1,2017.02.2,2017.03,2017.03.1,2017.03.2,2017.04,2017.04.1,2017.04.2,2017.05,2017.05.1,2017.05.2,2017.06,2017.06.1,2017.06.2,2017.07,2017.07.1,2017.07.2,2017.08,2017.08.1,2017.08.2,2017.09,2017.09.1,2017.09.2,2017.10,2017.10.1,2017.10.2,2017.11,2017.11.1,2017.11.2,2017.12,2017.12.1,2017.12.2,2018.01,2018.01.1,2018.01.2,2018.02,2018.02.1,2018.02.2,2018.03,2018.03.1,2018.03.2,2018.04,2018.04.1,2018.04.2,2018.05,2018.05.1,2018.05.2,2018.06,2018.06.1,2018.06.2,2018.07,2018.07.1,2018.07.2,2018.08,2018.08.1,2018.08.2,2018.09,2018.09.1,2018.09.2,2018.10,2018.10.1,2018.10.2,2018.11,2018.11.1,2018.11.2,2018.12,2018.12.1,2018.12.2,2019.01,2019.01.1,2019.01.2,2019.02,2019.02.1,2019.02.2,2019.03,2019.03.1,2019.03.2,2019.04,2019.04.1,2019.04.2,2019.05,2019.05.1,2019.05.2,2019.06,2019.06.1,2019.06.2,2019.07,2019.07.1,2019.07.2,2019.08,2019.08.1,2019.08.2,2019.09,2019.09.1,2019.09.2,2019.10,2019.10.1,2019.10.2,2019.11,2019.11.1,2019.11.2,2019.12,2019.12.1,2019.12.2,2020.01,2020.01.1,2020.01.2,2020.02,2020.02.1,2020.02.2,2020.03,2020.03.1,2020.03.2,2020.04,2020.04.1,2020.04.2,2020.05,2020.05.1,2020.05.2,2020.06,2020.06.1,2020.06.2,2020.07,2020.07.1,2020.07.2,2020.08,2020.08.1,2020.08.2,2020.09,2020.09.1,2020.09.2,2020.10,2020.10.1,2020.10.2,2020.11,2020.11.1,2020.11.2,2020.12,2020.12.1,2020.12.2,2021.01,2021.01.1,2021.01.2,2021.02,2021.02.1,2021.02.2,2021.03,2021.03.1,2021.03.2,2021.04,2021.04.1,2021.04.2,2021.05,2021.05.1,2021.05.2,2021.06,2021.06.1,2021.06.2,2021.07,2021.07.1,2021.07.2,2021.08,2021.08.1,2021.08.2,2021.09,2021.09.1,2021.09.2,2021.10,2021.10.1,2021.10.2,2021.11,2021.11.1,2021.11.2,2021.12,2021.12.1,2021.12.2,2022.01,2022.01.1,2022.01.2,2022.02,2022.02.1,2022.02.2,2022.03,2022.03.1,2022.03.2,2022.04,2022.04.1,2022.04.2,2022.05,2022.05.1,2022.05.2,2022.06,2022.06.1,2022.06.2,2022.07,2022.07.1,2022.07.2,2022.08,2022.08.1,2022.08.2,2022.09,2022.09.1,2022.09.2,2022.10,2022.10.1,2022.10.2,2022.11,2022.11.1,2022.11.2,2022.12,2022.12.1,2022.12.2,2023.01,2023.01.1,2023.01.2,2023.02,2023.02.1,2023.02.2,2023.03,2023.03.1,2023.03.2,2023.04,2023.04.1,2023.04.2,2023.05,2023.05.1,2023.05.2,2023.06,2023.06.1,2023.06.2,2023.07,2023.07.1,2023.07.2,2023.08,2023.08.1,2023.08.2,2023.09,2023.09.1,2023.09.2,2023.10,2023.10.1,2023.10.2,2023.11,2023.11.1,2023.11.2,2023.12,2023.12.1,2023.12.2,2024.01,2024.01.1,2024.01.2,2024.02,2024.02.1,2024.02.2,2024.03,2024.03.1,2024.03.2,2024.04,2024.04.1,2024.04.2,2024.05,2024.05.1,2024.05.2,2024.06,2024.06.1,2024.06.2,2024.07,2024.07.1,2024.07.2,2024.08,2024.08.1,2024.08.2,2024.09,2024.09.1,2024.09.2,2024.10,2024.10.1,2024.10.2,2024.11,2024.11.1,2024.11.2,2024.12,2024.12.1,2024.12.2,1997,1997.1,1997.2,1998,1998.1,1998.2,1999,1999.1,1999.2,2000,2000.1,2000.2,2001,2001.1,2001.2,2002,2002.1,2002.2,2003,2003.1,2003.2,2004,2004.1,2004.2,2005,2005.1,2005.2,2006,2006.1,2006.2,2007,2007.1,2007.2,2008,2008.1,2008.2,2009,2009.1,2009.2,2010,2010.1,2010.2,2011,2011.1,2011.2,2012,2012.1,2012.2,2013,2013.1,2013.2,2014,2014.1,2014.2,2015,2015.1,2015.2,2016,2016.1,2016.2,2017,2017.1,2017.2,2018,2018.1,2018.2,2019,2019.1,2019.2,2020,2020.1,2020.2,2021,2021.1,2021.2,2022,2022.1,2022.2,2023,2023.1,2023.2,2024,2024.1,2024.2
14,전북특별자치도,2579,1362,1217,2261,1150,1111,2364,1186,1178,2203,1116,1087,2085,1114,971,1992,1056,936,2112,1076,1036,2140,1124,1016,2078,1108,970,2198,1149,1049,2076,1071,1005,2182,1102,1080,2558,1357,1201,2425,1296,1129,2312,1209,1103,2072,1039,1033,2088,1042,1046,1894,937,957,1991,1085,906,2062,1079,983,2233,1188,1045,2109,1082,1027,2063,1038,1025,2042,1082,960,2481,1311,1170,2132,1097,1035,2227,1161,1066,2108,1074,1034,1997,1089,908,1786,950,836,1962,986,976,1931,1015,916,1996,1014,982,2011,1032,979,1998,990,1008,1935,987,948,2547,1291,1256,2296,1202,1094,2384,1216,1168,2054,1074,980,2041,1104,937,1865,962,903,1925,991,934,1956,1013,943,2122,1102,1020,1989,1028,961,2010,1054,956,1984,1031,953,2410,1214,1196,2000,1016,984,2080,1044,1036,1904,982,922,1808,908,900,1718,927,791,1643,859,784,1713,847,866,1806,957,849,1776,942,834,1672,899,773,1662,851,811,1955,1045,910,1725,885,840,1829,940,889,1639,860,779,1614,831,783,1391,732,659,1602,852,750,1550,806,744,1504,807,697,1546,822,724,1405,755,650,1455,751,704,1847,965,882,1591,786,805,1703,876,827,1524,781,743,1531,757,774,1428,755,673,1448,734,714,1396,712,684,1469,769,700,1513,778,735,1539,809,730,1448,768,680,1781,924,857,1519,815,704,1625,817,808,1429,711,718,1346,695,651,1346,708,638,1425,735,690,1341,667,674,1378,733,645,1415,721,694,1337,703,634,1315,652,663,1632,869,763,1284,684,600,1481,770,711,1319,690,629,1265,672,593,1248,671,577,1261,679,582,1267,653,614,1316,683,633,1310,660,650,1294,685,609,1068,574,494,1537,783,754,1330,689,641,1418,746,672,1275,672,603,1259,644,615,1223,615,608,1275,646,629,1323,708,615,1317,685,632,1253,634,619,1241,620,621,1120,570,550,1661,866,795,1417,744,673,1512,762,750,1438,750,688,1373,669,704,1274,680,594,1330,694,636,1528,795,733,1567,805,762,1583,813,770,1419,755,664,1126,573,553,1700,876,824,1344,685,659,1391,709,682,1352,702,650,1290,706,584,1119,585,...,1039,545,494,1019,495,524,1327,697,630,1137,599,538,1167,583,584,1095,561,534,1129,580,549,1055,549,506,1033,518,515,1014,522,492,1056,526,530,966,519,447,908,484,424,811,393,418,1124,578,546,1018,529,489,1048,559,489,938,495,443,955,473,482,944,479,465,937,460,477,938,452,486,958,494,464,855,415,440,869,451,418,764,395,369,994,502,492,916,444,472,897,470,427,866,439,427,832,424,408,799,424,375,810,411,399,838,427,411,818,410,408,807,422,385,784,390,394,640,328,312,859,435,424,712,352,360,811,421,390,810,437,373,783,374,409,727,358,369,693,364,329,733,390,343,739,360,379,746,385,361,724,369,355,634,344,290,743,387,356,656,347,309,739,359,380,739,401,338,690,360,330,608,313,295,675,338,337,694,341,353,699,332,367,642,324,318,636,317,319,644,318,326,737,381,356,629,302,327,651,331,320,675,333,342,616,334,282,623,310,313,651,309,342,610,356,254,628,334,294,588,302,286,543,264,279,524,280,244,695,347,348,586,284,302,625,308,317,589,285,304,529,257,272,596,292,304,604,296,308,577,265,312,596,296,300,577,284,293,575,280,295,483,254,229,688,363,325,536,269,267,587,307,280,517,260,257,520,257,263,558,269,289,580,293,287,583,322,261,503,250,253,548,262,286,486,230,256,516,277,239,614,310,304,586,300,286,549,292,257,506,247,259,552,270,282,556,286,270,550,302,248,564,311,253,573,287,286,626,304,322,572,288,284,532,276,256,26270,13614,12656,25849,13434,12415,24564,12706,11858,25173,13068,12105,22192,11446,10746,19215,10086,9129,18437,9490,8947,17257,8881,8376,15745,8290,7455,15571,8012,7559,17228,8906,8322,15878,8245,7633,15233,7847,7386,16100,8357,7743,16175,8290,7885,16238,8457,7781,14555,7506,7049,14231,7340,6891,14087,7225,6862,12698,6531,6167,11348,5780,5568,10001,5091,4910,8971,4589,4382,8165,4137,4028,7475,3836,3639,7032,3448,3584,6622,3359,3263,6780,3473,3307
15,전라남도,2685,1413,1272,2547,1286,1261,2457,1246,1211,2348,1203,1145,2290,1204,1086,2207,1171,1036,2256,1175,1081,2153,1129,1024,2203,1128,1075,2235,1149,1086,2309,1162,1147,2390,1178,1212,2480,1298,1182,2421,1243,1178,2517,1317,1200,2329,1141,1188,2099,1136,963,2008,1076,932,2189,1153,1036,2056,1076,980,2183,1154,1029,2216,1175,1041,2116,1114,1002,2227,1181,1046,2586,1342,1244,2271,1178,1093,2403,1234,1169,2239,1170,1069,2176,1129,1047,2018,1081,937,2148,1125,1023,1994,1073,921,2110,1138,972,2124,1120,1004,2216,1155,1061,2078,1033,1045,2679,1367,1312,2366,1245,1121,2423,1256,1167,2157,1146,1011,2109,1108,1001,1894,976,918,1944,1009,935,2123,1091,1032,2128,1114,1014,2156,1103,1053,2026,1095,931,2041,1088,953,2392,1287,1105,2070,1071,999,2306,1176,1130,2013,1039,974,1783,913,870,1624,868,756,1710,920,790,1730,925,805,1812,956,856,1793,905,888,1654,847,807,1701,845,856,2000,1089,911,1765,897,868,1881,982,899,1649,876,773,1587,836,751,1442,764,678,1564,827,737,1531,789,742,1514,763,751,1509,773,736,1454,748,706,1346,674,672,1761,899,862,1596,825,771,1638,877,761,1588,799,789,1498,781,717,1351,733,618,1434,778,656,1404,691,713,1578,885,693,1630,849,781,1480,747,733,1375,736,639,1821,982,839,1533,792,741,1673,878,795,1454,731,723,1464,779,685,1320,698,622,1385,745,640,1401,736,665,1370,709,661,1390,752,638,1236,639,597,1209,625,584,1572,789,783,1328,696,632,1548,765,783,1337,679,658,1261,673,588,1277,685,592,1260,645,615,1232,638,594,1249,656,593,1251,615,636,1342,697,645,1161,572,589,1501,754,747,1363,677,686,1467,745,722,1348,708,640,1350,699,651,1217,626,591,1270,648,622,1284,669,615,1326,681,645,1294,661,633,1322,672,650,1163,622,541,1687,865,822,1416,738,678,1544,815,729,1434,763,671,1409,733,676,1366,710,656,1367,693,674,1515,762,753,1629,850,779,1613,846,767,1525,790,735,1339,680,659,1698,855,843,1395,717,678,1503,751,752,1348,686,662,1294,688,606,1244,652,...,1145,589,556,1065,536,529,1451,749,702,1229,611,618,1335,687,648,1193,612,581,1104,565,539,1128,544,584,1142,587,555,1202,628,574,1113,561,552,1113,561,552,1048,539,509,922,497,425,1315,693,622,997,512,485,1203,618,585,1044,549,495,980,488,492,977,511,466,1017,549,468,991,511,480,1044,547,497,973,515,458,934,485,449,879,461,418,1077,567,510,978,514,464,1076,553,523,975,491,484,956,481,475,890,454,436,902,458,444,914,452,462,913,468,445,918,460,458,849,444,405,790,398,392,1117,572,545,920,452,468,955,485,470,924,495,429,931,468,463,837,432,405,909,454,455,866,444,422,891,435,456,884,409,475,829,455,374,769,416,353,955,502,453,825,424,401,910,465,445,793,418,375,807,428,379,769,386,383,868,435,433,833,411,422,814,421,393,751,381,370,725,371,354,688,337,351,884,438,446,683,356,327,744,377,367,699,344,355,735,367,368,676,370,306,749,386,363,738,344,394,708,367,341,632,290,342,640,332,308,542,281,261,805,419,386,663,338,325,698,347,351,661,359,302,642,342,300,566,282,284,693,354,339,686,339,347,766,380,386,642,331,311,566,289,277,500,250,250,784,402,382,674,339,335,712,357,355,623,343,280,639,337,302,638,318,320,629,293,336,670,319,351,668,336,332,673,327,346,585,301,284,533,264,269,737,353,384,686,367,319,668,340,328,651,318,333,662,328,334,669,347,322,727,363,364,699,344,355,687,342,345,687,349,338,735,390,345,617,310,307,28080,14444,13636,26841,14064,12777,26363,13778,12585,26046,13598,12448,22588,11752,10836,19242,10018,9224,18333,9600,8733,17256,9066,8190,15818,8110,7708,15905,8162,7743,17844,9245,8599,16363,8435,7928,15995,8186,7809,16654,8609,8045,16612,8448,8164,16990,8600,8390,15401,7819,7582,14817,7533,7284,15061,7725,7336,13980,7141,6839,12354,6439,5915,11238,5740,5498,10832,5517,5315,9738,4979,4759,8430,4252,4178,7888,4030,3858,7828,3936,3892,8225,4151,4074
16,경상북도,3362,1802,1560,3257,1751,1506,3343,1754,1589,3183,1677,1506,3024,1589,1435,2760,1498,1262,2978,1552,1426,3000,1595,1405,3002,1612,1390,3110,1635,1475,2978,1543,1435,3120,1645,1475,3333,1776,1557,3140,1683,1457,3371,1831,1540,3036,1597,1439,2798,1445,1353,2733,1409,1324,2791,1517,1274,2650,1451,1199,2802,1542,1260,2758,1438,1320,2724,1423,1301,2778,1495,1283,3165,1673,1492,2960,1564,1396,3320,1753,1567,2920,1563,1357,2728,1446,1282,2623,1391,1232,2730,1430,1300,2738,1503,1235,2939,1565,1374,2962,1583,1379,2889,1496,1393,2869,1510,1359,3362,1812,1550,3221,1633,1588,3292,1735,1557,2968,1580,1388,2973,1576,1397,2472,1295,1177,2714,1463,1251,2751,1491,1260,2881,1561,1320,2858,1539,1319,2882,1513,1369,2816,1503,1313,2955,1577,1378,2718,1410,1308,3023,1612,1411,2666,1419,1247,2595,1380,1215,2319,1244,1075,2313,1176,1137,2422,1288,1134,2425,1299,1126,2460,1279,1181,2298,1193,1105,2306,1216,1090,2517,1333,1184,2265,1206,1059,2564,1319,1245,2360,1291,1069,2208,1181,1027,2009,1128,881,2189,1162,1027,2073,1095,978,2025,1140,885,1987,1041,946,1936,1003,933,1889,992,897,2231,1169,1062,2165,1158,1007,2507,1341,1166,2264,1180,1084,2066,1074,992,1881,942,939,1921,1010,911,1955,1049,906,2128,1157,971,2207,1174,1033,2134,1139,995,1988,996,992,2206,1162,1044,2049,1093,956,2257,1188,1069,2193,1158,1035,1888,989,899,1774,953,821,1948,1076,872,1814,938,876,1884,998,886,2043,1108,935,1770,912,858,1727,902,825,2029,1082,947,1818,956,862,2076,1111,965,1897,951,946,1950,1046,904,1694,849,845,1795,936,859,1794,944,850,1879,1002,877,1919,985,934,1799,975,824,1689,894,795,2025,1058,967,1892,1007,885,2110,1141,969,1873,955,918,1857,1004,853,1782,904,878,1737,897,840,1812,977,835,1953,1018,935,1986,1072,914,1805,928,877,1735,889,846,2146,1128,1018,2032,1085,947,2272,1123,1149,2058,1071,987,2064,1062,1002,1906,993,913,1993,1059,934,2172,1082,1090,2172,1103,1069,2327,1195,1132,2097,1080,1017,1823,958,865,2318,1198,1120,1968,1011,957,2151,1145,1006,2034,1047,987,1908,946,962,1756,916,...,1694,843,851,1601,835,766,1996,1046,950,1732,915,817,1954,996,958,1818,941,877,1747,901,846,1690,904,786,1703,876,827,1705,857,848,1716,875,841,1677,859,818,1495,766,729,1383,718,665,1824,923,901,1502,746,756,1660,853,807,1497,764,733,1561,818,743,1388,717,671,1522,799,723,1513,785,728,1498,763,735,1376,720,656,1336,726,610,1280,639,641,1571,818,753,1336,711,625,1548,800,748,1325,683,642,1399,707,692,1341,719,622,1326,681,645,1351,716,635,1214,636,578,1263,633,630,1246,659,587,1159,622,537,1478,766,712,1230,616,614,1379,712,667,1214,630,584,1174,605,569,1224,642,582,1194,609,585,1110,565,545,1120,566,554,1239,602,637,1159,562,597,951,496,455,1273,649,624,1131,579,552,1172,594,578,1118,579,539,1099,572,527,1015,496,519,1051,529,522,1017,508,509,1123,613,510,1066,553,513,945,469,476,863,432,431,1126,560,566,1011,512,499,1126,575,551,1068,505,563,992,504,488,991,511,480,1040,543,497,1065,553,512,1001,484,517,889,465,424,961,500,461,775,393,382,1118,577,541,920,481,439,1061,534,527,955,483,472,968,494,474,832,422,410,879,457,422,975,486,489,989,496,493,959,481,478,885,462,423,770,404,366,1035,520,515,935,512,423,914,515,399,819,447,372,874,426,448,797,397,400,834,423,411,808,413,395,799,419,380,859,457,402,770,395,375,742,366,376,996,521,475,844,428,416,835,428,407,837,420,417,839,412,427,789,406,383,879,457,422,924,496,428,861,436,425,873,471,402,877,469,408,779,413,366,37117,19653,17464,34914,18607,16307,34843,18477,16366,35190,18701,16489,30500,16093,14407,26022,13891,12131,25447,13389,12058,23553,12477,11076,22339,11731,10608,22567,11850,10717,25062,12939,12123,23538,12238,11300,22373,11707,10666,23700,12262,11438,24250,12502,11748,24635,12758,11877,22206,11538,10668,22062,11437,10625,22310,11453,10857,20616,10654,9962,17957,9253,8704,16079,8385,7694,14472,7371,7101,12873,6573,6300,12045,6105,5940,11311,5777,5534,10186,5290,4896,10333,5357,4976

In [7]:
df_kosis.info()

<class 'pandas.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Columns: 1093 entries, 시군구별 to 2024.2
dtypes: str(1093)
memory usage: 162.4 KB